_target_: src.context_matters.pipelines.delta_pipeline.DeltaPipeline

# Delta pipeline args
generate_domain: True          # Perform PDDL domain generation VS use the ground truth one
ground_in_sg:    True           # Perform our simulated execution/grounding to test feasibility of generated plan
goal_decomposition: True        # Decompose goals into subgoals
sg_pruning: True                # Prune scene graph to reduce complexity
intermediate_validation: True   # Early stopping if generated PDDL domain/problem is invalid (to save useless LLM calls)
whole_problem_planning: False   # Plan the whole problem at once (before decomposing into subgoals)

# Parameters for llm calls (NOT USED IN DELTA, THE DEFAULT ONES ARE USED)
temperature: 0.0
top_p: 1.0