_target_: src.context_matters.pipelines.sayplan_pipeline.SayPlanPipeline

# SayPlan pipeline args
generate_domain: False
ground_in_sg:    False
max_debug_attempts: 4
max_search_attempts: 10
episodes: 1

# Parameters for llm calls
temperature: 0.0
top_p: 1.0