defaults:
  - _self_
  - pipeline: cm
  - agent: gpt

base_path: ${hydra:runtime.cwd}
data_path: ${base_path}/dataset
res_path: ${base_path}/results
metrics_res_path: ${base_path}/metrics_results


splits:
  - dining_setup
  - general
  - house_cleaning
  - laundry
  - office_setup
  - pc_assembly